buildscript {
    ext {
        springBootVersion = '3.4.4'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

apply plugin: 'eclipse'
apply plugin: 'maven-publish'
apply plugin: 'java'
apply plugin: 'java-library'
apply plugin: 'org.springframework.boot'

//README uncomment the line below to use 'gradle build' to package a war.
//This file is shipped as a java plugin project not a war plugin project because
//other projects use jitpack to include the snooze api as a dependency.  If
//it were a war project by default jipack would serve the war not the jar which
//would be useless.
//apply plugin: 'war'

project.docsDirName = '../docs/0.3.x/'

configurations.all { resolutionStrategy.cacheChangingModulesFor 0, 'seconds' }


version = '0.4.5'
group = 'com.github.RocketPartners'
sourceCompatibility = JavaVersion.VERSION_17

ext {
    archiveRepo = "https://maven.pkg.github.com/RocketPartners/artifacts"
    archiveRepoUser = System.env.GHP_USER
    archiveRepoPassword = System.env.GHP_PASSWORD
    awsSdkV2Version = '2.41.34'
}

repositories {
    mavenLocal()
    maven {
        url archiveRepo
        credentials {
            username archiveRepoUser
            password archiveRepoPassword
        }
    }
    maven { url "https://s3.amazonaws.com/redshift-maven-repository/release" }
    mavenCentral()
}

dependencies {

    api "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    api "org.springframework.boot:spring-boot-starter-actuator:$springBootVersion"
    api "org.springframework.boot:spring-boot-starter-jdbc:$springBootVersion"
    api "org.springframework.boot:spring-boot-starter-test:$springBootVersion"

    api 'dev.akkinoc.spring.boot:logback-access-spring-boot-starter:4.4.1'
    api 'ch.qos.logback.contrib:logback-json-classic:0.1.5'
    api 'ch.qos.logback.contrib:logback-jackson:0.1.5'
    api 'net.logstash.logback:logstash-logback-encoder:8.0'

    implementation 'com.sun.xml.bind:jaxb-impl:4.0.0'
    implementation 'jakarta.xml.bind:jakarta.xml.bind-api:2.3.3'

    api group: 'org.apache.commons', name: 'commons-collections4', version: '4.3'
    api group: 'org.apache.commons', name: 'commons-lang3', version: '3.8.1'
    api group: 'org.apache.commons', name: 'commons-csv', version: '1.4'

    api group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.5'
    api group: 'org.apache.httpcomponents', name: 'httpmime', version: '4.5.5'

    //aws libs
    api "software.amazon.awssdk:s3:$awsSdkV2Version"
    api('com.amazonaws:aws-java-sdk-dynamodb:1.11.390') {
        //TODO: remove exclude with https://circlek.atlassian.net/browse/LIFT-1805
        exclude group: "com.amazonaws", module: "aws-java-sdk-s3"
    }
    api 'com.amazonaws:aws-java-sdk-kinesis:1.11.390'
    api 'com.amazonaws:aws-lambda-java-core:1.2.0'
    api 'com.amazonaws:aws-java-sdk-rds:1.11.542'

    // required for the Redis client
    api group: 'redis.clients', name: 'jedis', version: '5.2.0'

    //drivers for supportd DBs
    api group: 'com.zaxxer', name: 'HikariCP', version: '4.0.3' //required connection pool libs
    api group: 'mysql', name: 'mysql-connector-java', version: '5.1.34'
    api group: 'com.h2database', name: 'h2', version: '1.4.197'
    api 'org.postgresql:postgresql:42.1.4'
//	 https://mvnrepository.com/artifact/com.amazon.redshift/redshift-jdbc42-no-awssdk
    compileOnly group: 'com.amazon.redshift', name: 'redshift-jdbc42-no-awssdk', version: '1.2.10.1009'

    // Beware of changing the redshift driver version. Newer versions of this driver are not thread-safe
    // Version 1.2.10.1009 is thread-safe
    // https://stackoverflow.com/questions/52884036/java-sql-sqlnontransientexception-amazonjdbc10900-not-all-parameters-have

    //scripting with javascript via graalvm (from oracle and newer than rhino/nashorn)
    api 'net.jodah:expiringmap:0.5.8'
    api group: 'org.graalvm', name: 'graal-sdk', version: '1.0.0-rc7'
    api group: 'com.oracle.truffle', name: 'truffle-api', version: '1.0.0-rc7'
    api files('libs/graaljs.jar') //does not appear to be in maven yet
    api files('libs/tregex.jar')  //does not appear to be in maven yet

    //scripting with velocity engine
    api group: 'org.apache.velocity', name: 'velocity-engine-core', version: '2.0'

    api 'junit:junit:4.12'
}


/************************************************************
 * Ensuring source directories are created if they do not 
 * already exist when running 'gradle eclipse'
 */
eclipse {
    classpath {
        file {
            tasks.eclipse.dependsOn(cleanEclipseClasspath)
            tasks.eclipse.dependsOn("create-dirs")
        }
    }
}


/************************************************************
 * This task should be used when creating a new project as
 * it will create all source and resource directories.  This
 * task is automatically executed during the 
 * 'gradle eclipse' command.
 */
task "create-dirs" {
    doLast {
        sourceSets*.java.srcDirs*.each { it.mkdirs() }
        sourceSets*.resources.srcDirs*.each { it.mkdirs() }
    }
}

javadoc {
//   exclude "**/utils/**"
}

test {
    exclude '**/*'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            credentials {
                username archiveRepoUser
                password archiveRepoPassword
            }
            url archiveRepo
        }
    }
}

tasks.register("getVersion") {
    doLast {
        println(project.version)
    }
}
