apply plugin: 'eclipse'
apply plugin: 'maven-publish'
apply plugin: 'java'
apply plugin: 'java-library'

//README uncomment the line below to use 'gradle build' to package a war.
//This file is shipped as a java plugin project not a war plugin project because
//other projects use jitpack to include the snooze api as a dependency.  If
//it were a war project by default jipack would serve the war not the jar which
//would be useless.
//apply plugin: 'war'

project.docsDirName='../docs/0.3.x/'

configurations.all { resolutionStrategy.cacheChangingModulesFor 0, 'seconds' }

version = '0.3.6.15'
group = 'com.github.RocketPartners'
sourceCompatibility = JavaVersion.VERSION_17

ext {
   archiveRepo = "https://maven.pkg.github.com/RocketPartners/artifacts"
   archiveRepoUser = System.env.GHP_USER
   archiveRepoPassword = System.env.GHP_PASSWORD
   junitVersion = '5.8.1'
   awsSdkV2Version = '2.41.34'
}

repositories {
   mavenLocal()

   maven {
      url archiveRepo
      credentials {
         username archiveRepoUser
         password archiveRepoPassword
      }
   }

   mavenCentral()
   // maven { url 'https://jitpack.io' }
   maven { url "https://s3.amazonaws.com/redshift-maven-repository/release" }
}

dependencies {

   if (gradle.ext.rckt_snooze['addFortJProjectToClasspath']) {
      api findProject(":fort_j")
   }
   else {
      api "com.github.wellsb1:fort_j:1.0.x"
   }

   if (gradle.ext.rckt_snooze['addFortWProjectToClasspath']) {
      api findProject(":fort_w")
   }
   else {
      api "com.github.wellsb1:fort_w:1.0.x"
   }

   if (gradle.ext.rckt_snooze['addFortSProjectToClasspath']) {
      api findProject(":fort_s")
   }
   else {
      api "com.github.wellsb1:fort_s:1.1.x"
   }

   api("com.github.wellsb1:fort_fusion_vtl:1.0.0") {
      exclude group: "javax.servlet", module: "javax.servlet-api"
   }

   api group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.55'

   api group: 'com.mchange', name: 'mchange-commons-java', version: '0.2.11'

   api group: 'commons-codec', name: 'commons-codec', version: '1.10'
   api group: 'commons-collections', name: 'commons-collections', version: '3.2.1'
   api group: 'org.apache.commons', name: 'commons-csv', version: '1.4'
   api group: 'commons-httpclient', name: 'commons-httpclient', version: '3.1'
   api group: 'org.apache.commons', name: 'commons-lang3', version: '3.4'

   api group: 'com.zaxxer', name: 'HikariCP', version: '3.3.1'

   // required for the Redis client
   api group: 'redis.clients', name: 'jedis', version: '5.2.0'

   api "software.amazon.awssdk:s3:$awsSdkV2Version"
   api "software.amazon.awssdk:dynamodb:$awsSdkV2Version"
   api "software.amazon.awssdk:firehose:$awsSdkV2Version"
   api "software.amazon.awssdk:rds:$awsSdkV2Version"

   // Beware of changing the redshift driver version. Newer versions of this driver are not thread-safe
   // Version 1.2.10.1009 is thread-safe
   // https://stackoverflow.com/questions/52884036/java-sql-sqlnontransientexception-amazonjdbc10900-not-all-parameters-have
   api group: 'com.amazon.redshift', name: 'redshift-jdbc42-no-awssdk', version: '1.2.10.1009'

   api group: 'com.auth0', name: 'java-jwt', version: '3.1.0'

   api group: 'ch.qos.logback', name: 'logback-classic', version: '1.1.11'

   // springboot 3 requires Jakarta EE 10 at minimum
   // https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee
   api "jakarta.platform:jakarta.jakartaee-api:10.0.0"

   api 'net.jodah:expiringmap:0.5.8'
   api group: 'org.graalvm', name: 'graal-sdk', version: '1.0.0-rc7'
   api group: 'com.oracle.truffle', name: 'truffle-api', version: '1.0.0-rc7'
   api files('libs/graaljs.jar')
   api files('libs/tregex.jar')


   api group: 'org.apache.velocity', name: 'velocity-engine-core', version: '2.0'

    testImplementation group: 'org.hamcrest', name: 'hamcrest-all', version: '1.3'
    testImplementation group: 'org.hamcrest', name: 'hamcrest', version: '2.2'
    testImplementation group: 'com.github.tomakehurst', name: 'wiremock', version: '2.27.2'
    testImplementation "org.junit.jupiter:junit-jupiter:$junitVersion"
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.9.2'
    testImplementation 'org.mockito:mockito-junit-jupiter:4.3.1'
    testImplementation 'org.mockito:mockito-inline:4.3.1'
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junitVersion"

}

test {
    useJUnitPlatform()
}


/************************************************************
 * Ensuring source directories are created if they do not
 * already exist when running 'gradle eclipse'
 */
eclipse {
   classpath {
      file {
         tasks.eclipse.dependsOn(cleanEclipseClasspath)
         tasks.eclipse.dependsOn("create-dirs")
      }
   }
}



/************************************************************
 * This task should be used when creating a new project as
 * it will create all source and resource directories.  This
 * task is automatically executed during the
 * 'gradle eclipse' command.
 */
task "create-dirs" {
   doLast {
      sourceSets*.java.srcDirs*.each { it.mkdirs() }
      sourceSets*.resources.srcDirs*.each { it.mkdirs() }
   }
}

javadoc {
   exclude "**/utils/**"
   exclude "**/evo/**"
}

publishing {
   publications {
      mavenJava(MavenPublication) {
         from components.java
      }
   }
   repositories {
      maven {
         credentials {
            username archiveRepoUser
            password archiveRepoPassword
         }
         url archiveRepo
      }
   }
}

tasks.register("getVersion") {
    doLast {
        println(project.version)
    }
}
